# Performance DR Environment Configuration

elasticsearch:
  host: elasticsearch-perfdr.example.com
  port: 9200
  scheme: https
  # username: ${ES_USERNAME}
  # password: ${ES_PASSWORD}
  verify_certs: true

stop_on_error: true
report_file: ./reports/perfdr-execution-report.json
